### ISSUE TITLE
Fix %code% variable

### ISSUE THREAD

**Issue by ai** [ramoona/postcss-banks-db#2]
We generate `bank.code` dynamically, so it is missed in `banksDB.data`.

So `.billing-form.is-%code%` doesn’t work.

**Comment by ai** [comment]
Also we should add this case to tests, because `%code%` is magic field :).

**Comment by ramoona** [comment]
fixed in [release 0.3.0](https://github.com/ramoona/postcss-banks-db/releases/tag/0.3.0) :P

**Comment by ai** [comment]
Tests ;)
